### ISSUE TITLE
Link to terms/instructions

### ISSUE THREAD

**Issue by bast** [constructicon/russian#15]
- Add links for terms - use the csv tables for usage labels, syntactic terms, semantic terms that appear in the descriptions of individual constructions.
- The link should open a new tab.
- Originally we considered using tool-tips or opening new windows.

Example: If one clicks or brings the pointer to the term Colloquial, there should be a link redirecting to the explanations on instructions page.

**Comment by bast** [comment]
Parking this a bit ...
- Needs more thought to plan where the data sits since this feature mixes the yaml data from `russian-data` with the markdown instruction page which resides here on the app.
- Personally I wonder whether this is even necessary. If everything essential is on the instructions page, why do we need these extra links for every term?

**Comment by Labrus** [comment]
I agree. Let's drop this linking feature.
