### ISSUE TITLE
Advanced search: change items in menus to alphabetical order

### ISSUE THREAD

**Issue by lajanda** [constructicon/russian#32]
The items in the pull-down menus on the Advanced Search page are in what appears to be random order.
For example, under Morphology, the order is: NP, Nom, Cop, Noun, Cl.
Perhaps these could be made alphabetical?
Also, there seems to be a problem with this item:
288
NAME NP (размером/величиной) с NP-Acc - Собака была размером с лошадь.
It generates two menu items in Morphology, one is: NP (размером, and the other is: величиной) с NP.
Maybe the / messed it up?
And there are many items with the label “NA”, I don't understand how those work.

**Comment by bast** [comment]
See also #30.

**Comment by bast** [comment]
Please don't put two problems into one issue. I moved the latter into #33. The rest is duplicate with #30.
