### ISSUE TITLE
Syntactic function of anchor

### ISSUE THREAD

**Issue by lajanda** [constructicon/russian#34]
I have tried several items and none return any results.
Furthermore, there seem to be duplicates, with both 
Clause and clause 
Adj and adjective
Conj and Conjunction

And the order is rather random rather than alphabetical.

**Comment by bast** [comment]
I see 3 problems here in one issue:
- Some searches do not seem to return any hits. Please give an example of how I can reproduce it.
- Duplicates: this is a data problem
- Alphabetic ordering: this is a known problem (#30).

**Comment by lajanda** [comment]
Sorry. I promise to put only one issue in each issue in the future.
And here is a screenshot. When I select an item under Syntactic function of anchor, no examples are returned. It works well for the others I have checked so far: Morphology and Syntactic type of construction.

--laura

[cid:65bc6dcf-cc2e-48de-81bc-489fdde6d92c]

________________________________

**Comment by bast** [comment]
The screenshot seems to not have arrived here. I think you need to upload via the web interface (there is a link at the bottom of email). But if this affects any item under "Syntactic function of anchor", then I can dig into why that is.

**Comment by lajanda** [comment]
![Screenshot 2020-12-28 at 14 52 10](https://user-images.githubusercontent.com/26918586/103218760-46c29000-491c-11eb-9ff1-868ebbf5b852.png)
Here is the screenshot again. I chose the first item in the menu and got no search results. I tried several others too.
