### ISSUE TITLE
Semantic types returns no search results

### ISSUE THREAD

**Issue by lajanda** [constructicon/russian#36]
We get no search results when we choose semantic types.
You can see that if you choose Mirative (or any other item under Semantic types).
![Screenshot 2020-12-28 at 15 02 09](https://user-images.githubusercontent.com/26918586/103219327-acfbe280-491d-11eb-8ac8-2a958517ceb0.png)

**Comment by bast** [comment]
I confirm that this is currently not working. At this moment I don't know why.

**Comment by bast** [comment]
Looks "right" from the inside. I suspect that something goes wrong when creating the search index.
