### ISSUE TITLE
Individual html addresses (links) to individual constructions

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#40]
This is rather a question whether this is possible to program. Now, there is one and the same address to the resource https://constructicon.github.io/russian/ and it remains the same if we open an individual construction, for example we click on construction 3 in search window on Browse, open its description, and the link remains the same https://constructicon.github.io/russian/. Colleagues from our project team ask me if we Han make it so that each construction would have an individual https address that we can use when referring to that specific construction. In particular, this is relevant when they try add cross-references to individual constructions in our resource from their different resource with related content. In our old Swedish interface, this was the case, for example a construction "NP-Acc_звать_NP-Ins/Nom" – мальчика звать Юрой has the address https://spraakbanken.gu.se/karp/#?mode=konstruktikon-rus&lang=eng&advanced=false&hpp=25&extended=and%7Crus-construction%7Cequals%7C&searchTab=special&page=1&search=sense%7C%7Ckonstruktikon-rus--NP-Acc_звать_NP-Ins%2FNom&map=false, and so on. Is it possible to have individual HTML addresses to our constructions by adding, let's say, the ID number of a construction to the resource HTML address, for example for the construction #3 the address could be https://constructicon.github.io/russian/3 or any other possible way would work for us too.

**Comment by bast** [comment]
It's technically definitely possible and I understand how this can be useful to refer to individual construction.

**Comment by Labrus** [comment]
This is great news for us! We need this very much.

**Comment by bast** [comment]
We should discuss however how this should behave. Should this then yield a static result showing that one constructicon? And if people want to search, they would navigate away from it? In other words how this would fit to the overall menus and browsing.

**Comment by Labrus** [comment]
I discussed this with Laura today. Laura and I really like how this looks like now. When the users opens a description of a construction, he can still go to the window and pick another construction to open, on the same page. It seems that implementing individual html addresses for individual constructions would disturb this what we have now. In this case, we suggest that we should rather drop this issue and keep it the way we have it now. If someone wants to find an individual construction, it is possible to do this by ID number by scrolling through the list in the search window, and this should be enough. We do not have to meet the needs of other resources, especially if they can refer to our constructions by ID numbers. In other words, we can close this issue.
