### ISSUE TITLE
Add search for constructions by their ID number

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#41]
In Browse, it is possible to search for constructions by typing in any string, and the search applies to the list of "formulas" (names) and "illustrations". We would like to add an option that it is possible to type in a number of a construction (ID number in column D in our google doc database) and find the construction that that number is assigned to. Each construction has an individual ID number. Even if the search a construction with ID number "3" would deliver a list of constructions whose ID numbers contain 3, like 30, 33, 1003, etc. this would still work for us.

**Comment by Labrus** [comment]
Now if the user types a number, the search returns results with numbers that appear in names and illustrations. So, if the search by ID number will be used in the same search window, this can disturb the existing search. We suggest that we add a separate search window in Browse, preferably placed under the window "Search in names and illustrations". And this windows would be called "Search by ID number". And it would only address the ID numbers of constructions (column D in the database).

**Comment by bast** [comment]
But do we really want to search by numbers or do we want #40 or both?

**Comment by Labrus** [comment]
We agree. Let us drop this search option by ID number. One can scroll through the list in the window instead. We want #40.
