### ISSUE TITLE
Search in Browse does not deliver all search results

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#42]
The search for constructions in Browse does not show all search results that should be available. For example, we search for Dat (dative case), and get only a few results, there should be many more. Our students have "cleaned" the column E with formulas (names of constructions) for possible misspellings, and when the data will be read into the website, the search might work better.
<img width="1228" alt="Screen Shot 2021-01-13 at 13 43 09" src="https://user-images.githubusercontent.com/63615172/107614975-a1554880-6c4b-11eb-9add-23f51a8d474b.png">

**Comment by bast** [comment]
Can you please list one or two results which should show up but don't?

**Comment by Labrus** [comment]
My search in the database returns 238 results including 
7 - NP-Nom Cop похожий-Short на NP-Acc (NP-Ins/по NP-Dat) - Вася похож на папу.
16 - (NP-Dat) грех Cop VP-Inf - Грех обижаться на взрослых.
17 - (NP-Dat) давно пора Cop VP-Inf - Детям давно пора поесть.
54 - NP-Nom велеть NP-Dat (не) VP-Inf - Мать велела сыну учиться.
89 - NP-Nom Cop всем Noun-Dat.Pl ~Noun-Nom - Всем борщам борщ.
682 - (а) как же PronPers-Dat не быть, если Cl - У вас такая чистота! А как же ей не быть, если в доме ребёнок.
698 - Cl, а PronPers-Dat-то что? - Хочу и рисую, а вам-то что?

I can see that those cases that have -Dat and Dat- (because Dat is the Dative case on nouns NP, pronouns PronPers) do not appear as results now.
