### ISSUE TITLE
In Advance search, restrict the search to specific columns

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#43]
We illustrate this general issue with the following example. In we chose Loc (=locative case) in Morphology window, we get more results than needed, some constructions that appear as results do not contain "Loc" in their name (formula), for example #272, and they appear as results because it also has Location as a tag in Semantic role (a separate column in the database). This means that when searching for tags inside Morphology, the engine is pulling overlapping tags (e.g. Loc vs Location) from other columns in the database. Instead, the search should be restricted to a single column that corresponds to a give search category (for example, only Morphology, or any other)
<img width="1220" alt="Screen Shot 2021-02-11 at 09 33 34" src="https://user-images.githubusercontent.com/63615172/107615547-af579900-6c4c-11eb-93a4-effc9583d392.png">
<img width="357" alt="Screen Shot 2021-02-11 at 09 37 59" src="https://user-images.githubusercontent.com/63615172/107615878-3efd4780-6c4d-11eb-8ae5-e2775d7b62d1.png">

**Comment by bast** [comment]
I plan to fix this one in time. But this will require some work inside the code.
