### ISSUE TITLE
Update the YAML structure to reflect the change in the database of UD structure column

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#45]
Our colleague has now split the column UD structure into two columns with the same organization of information. Basically, what used to be called STRUCTURE in UD is now split in the database in two columns: Dependency Structure (column AJ) and Dependency Structure of Illustration (column AK). This is additional information, it is not included into search but it is included in the description of constructions if one presses the button "Additional information".
Each filed in this column can contain several strings (results of UD analyses) that will be separated by the sign "+". I can ask Olya to change this to a different symbol if needed. On the website they should be placed each in a separate line. Therefore, I suggest the YAML structure to be as follows:

column AJ: Dependency Structure   
•	variant 1
•	variant 2
•	variant 3
column AK: Dependency Structure of Illustration
•	variant 1
•	variant 2
•	variant 3

**Comment by bast** [comment]
I will adapt the conversion script to parse "+" but in future please use a consistent separator. Now we have comma, plus, semicolon. And the more we have, the more likely it is to misinterpret something that is not supposed to be a separator.

**Comment by bast** [comment]
Data updated but I need to move it below "additional information" still.
