### ISSUE TITLE
Visual design of Browse page: make the results of search more visible when they appear, relocate the logo, use original logo with words

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#46]
In Browse, when you get the search results, they should somehow be visible on the same page without that the user needs to scroll down to see the information that just appeared on the page. Now, because one cannot see the changes on the page after you applied search, it gives a wrong impression that nothing happened. Maybe after search results have appeared, the user can "fly" to the place on the page where the results of search can be seen (information on the construction below the search window)? Or move everything we have on the page (search window) slightly upward, so that the search result will be seen when it appears at the bottom of the page? or add words - "Scroll down to see the results"?

**Comment by bast** [comment]
The user "flying down to" the result: this I would find a bit annoying as user because when browsing the results, it would move me away every time. But it's your call.

I can easily rearrange the layout of the page but please let me know what I should change: where to reduce the space. We can also discuss this over video/ screenshare.

**Comment by Labrus** [comment]
We agree with you that we drop the flying cursor. If this is not a problem for you too rearrange the layout of the page, we will go for it. I will provide some images here after Laura approves them on March 11.

**Comment by Labrus** [comment]
We suggest that we rearrange the layout of Browse page to go back to the original idea and make it more similar to SMARTool. We should use the original logo of the Russian Constructicon that contains the name of the resource. It should be placed in the left top corner of the page, because this way it will not be on periphery but in the focus of the page. The names of the tabs are moved to the right of the logo. Maybe make the grey field where the tab names are a little darker and the letters in the names of tabs black. The search window is slightly moved upward to provide more space at the bottom when the search results come up. The institutional logos are visible on the same page and can be captured by screenchot of the same page that we can use in articles and conference presentations.

<img width="1372" alt="Browse wanted design" src="https://user-images.githubusercontent.com/63615172/110771610-fd1aed80-825a-11eb-9ce4-48c8e3721015.png">

**Comment by Labrus** [comment]
The original logo is available here https://github.com/Labrus/Russian-Constructicon-Design/blob/master/Russian_vector_logo.pdf and we also have it in high resolution in other formats if needed.

**Comment by bast** [comment]
This is now hopefully done.
