### ISSUE TITLE
Visual design of Browse page: color the illustrations in the window to the right

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#49]
In the window to the right edge, on Browse, the formulas of constructions visually "fuse" with their illustrations. Maybe we can add a slight difference in color of the text for illustrations? Laura suggests that we use the dark blue color from the set of colours that appear on the logo image, so that the text can still be seen well.
Thus, in construction 3, for example, the text "А как же мама?" that comes after "-" will be given in the dark blue color.
(а) как же NP-Nom? - А как же мама?

**Comment by bast** [comment]
The coloring was suggested before but I am unsure how to do it (using the library that is used). But one thing that is definitely doable is to add some spacing.
