### ISSUE TITLE
In Instructions: incorporating the instructions in Russian into the layout of the page

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#51]
<img width="1336" alt="Instructions page wanted" src="https://user-images.githubusercontent.com/63615172/110773396-ff7e4700-825c-11eb-8f1d-a44459f7fa4f.png">

We need to provide the same instructions that we have in English - also in Russian. On Instructions page, we can put all  Russian instructions after ALL English instructions, and an additional list of sections for Russian (for example, as on the picture above) would be a shortcut way to access those portions of the text. Do you find this solution nice? If not, please let me know what is best to do. I plan to provide all Russian text in Markdown by March 19. Should I copy paste it to https://github.com/constructicon/russian/blob/main/content/instructions.md ?

**Comment by bast** [comment]
So you would like these side by side? English left, Russian right?

**Comment by Labrus** [comment]
The content yes, this way, but for the text we imagine that first all instructions will be given in English and then all instructions will be given in Russian on the same long page, if you think it is ok. And these blue links in the list of content would bring the user to the relevant part of instructions, as you have done this for English already. What do you think?

**Comment by Labrus** [comment]
If you think that Russian part can be provided in a different way, fo example, on a separate page, please share you ideas with me. We want to make it simple and not time consuming for you.

**Comment by bast** [comment]
The table of contents is automatically generated. I am unsure whether two different ToCs can be generated from one single page. I need to check but don't yet have the time. Having this on two pages is certainly possible.

**Comment by Labrus** [comment]
Then maybe we can just go for this option and have them on two pages? Should we call the two pages as "Instructions in English" and "Instructions in Russian" accordingly?

**Comment by Labrus** [comment]
+++
+++

# Инструкции

## 1. Объяснение страниц сайта

### Стартовая страница (Browse)

На этой странице пользователь может просмотреть весь список из более чем 2200 конструкций, включенных в Русский Конструктикон. Запись каждой конструкции в списке включает ее Номер, Имя (обобщенную формулу) и Иллюстрацию. Некоторые номера конструкций не следуют подряд друг за другом. Это не ошибка, а результат длительного процесса сбора конструкций и удаления дублирующих друг друга единиц на более поздних стадиях.

Список конструкций помещен в отдельном окне справа, где его можно прокрутить вниз или вверх, выбрать из него отдельную конструкцию и нажатием на нее открыть ее описание. Под описанием конструкции расположена кнопка “Show additional information”, которая открывает дополнительную информацию о конструкции.

Пользователь может искать конструкции, вводя любую последовательность символов  в поисковую строку слева. Здесь можно задать точный поиск по элементам, входящим в состав конструкции. Можно ввести ввести слово или словоформу или обозначения категорий типа NP, Dat, Pfv (см. список сокращений). Результаты поиска появятся в окне справа, где прежде помещался весь список конструкций.

NB! Загрузка страницы может  занять несколько секунд. Если вы ждете слишком долго, попробуйте открыть сайт в другом браузере.


### Дневная порция (Daily Dose)

На этой странице пользователь может выбрать уровень владения языком и нажатием кнопки “Get random records“ получить случайную подборку из пяти конструкций этого уровня. Такая обозримая порция конструкций может использоваться студентами РКИ для самостоятельной работы. Как и на стартовой странице, пользователь видит Номер, Имя и Иллюстрацию конструкции, а полную информацию о конструкции получает при нажатии на нее.


### Продвинутый поиск (Advanced Search)

На этой странице пользователь может задать поиск конструкций по различным параметрам, которые можно комбинировать. Описание категорий, доступных для поиска, смотри в отдельных разделах инструкций.


### Инструкции (Instructions)

Эта страница содержит инструкции для пользователей.


### О проекте (About)

Эта страница содержит информацию о ресурсе и разработчиках.

---

## 2. Abbreviations and symbols

Each construction is represented by its name and a short illustration: e.g.
**найти-Pst NP-Acc!** _Нашли развлечение!_ (‘What a bad way to amuse yourself!
[lit. found amusement]’). The name of a construction is a short morphosyntactic
formula that usually includes fixed lexical parts as well as grammatical slots
indicated by means of common abbreviations like NP, VP, etc. When necessary, we
specify morphological characteristics of the fixed lexeme or a slot, where we
use abbreviations according the Leipzig Glossing rules.

|   Gloss     |     Explanation     |
|-------------|---------------------|
|      1      |    First person     |
|      2      |    Second person    |
|      3      |    Third person     |
|      ()     |    Optional element |
|      /      |    Alternative elements |
|      ~      |    Reduplication (repetition of the same word or morpheme) |
|      Acc    |    Accusative       |
|      Adj    |    Adjective        |
|      Adv    |    Adverb           |
|      Anim   |    Animate          |
|      Bare   |    Bare stem of a verb (e.g. _прыг, шлеп, скок_) |
|      Cconj     |    Coordinating conjunction |
|      Cl     |    Clause |
|      Cmp     |    Comparative |
|      Cop     |    Copula |
|      Cvb     |    Converb (verbal adverb) |
|      Dat     |    Dative |
|      F       |    Feminine |
|      Fut     |    Future   |
|      Gen     |    Genitive |
|      Gen2    |    "Second" genitive (Partitive genitive) |
|      Imp     |    Imperative |
|      Inan    |    Inanimate |
|      Ind     |    Indicative |
|      Inf     |    Infinitive |
|      Ins     |    Instrumental |
|      Ipfv    |    Imperfective |
|      Loc     |    Locative |
|      M       |    Masculine |
|      N       |    Neuter |
|      N-      |    Non- (e.g. Nsg=nonsingular, Npst=Nonpast) |
|      Intj    |    Interjection |
|      Nom     |    Nominative |
|      Noun    |    Noun |
|      NP      |    Noun phrase |
|      NumColl |    Collective numeral (e.g. _двое, трое_) |
|      NumCrd  |    Cardinal numeral (e.g. _один, два_) |
|      NumOrd  |    Ordinal numeral (e.g. _первый, второй_) |
|      Pfv     |    Perfective  |
|      Pl      |    Plural      |
|      PP      |    Prepositional phrase |
|      Pred    |    Predicative |
|      Prep    |    Preposition |
|      PronDem |    Demonstrative pronoun (e.g. _это, то_) |
|      PronInt |    Interrogative / relative pronoun (e.g. _кто, что, какой, который, каков, чей, когда, где, куда_) |
|      PronPers|    Personal pronoun (e.g. _я, мы, ты, вы, он, она, оно, они_) |
|      PronPoss    |    Possessive pronoun (e.g. _мой, твой, наш, его, ее, их_) |
|      Prs     |    Present     |
|      Pst     |    Past        |
|      PtcpAct |    Active participle |
|      PtcpPass|    Passive participle |
|      Sbjv    |    Subjunctive |
|      Sconj   |    Subordinating conjunction |
|      Sg      |    Singular |
|      Short   |    Short form |
|      Superl  |    Superlative |
|      Verb    |    Verb     |
|      Voc     |    Vocative |
|      VP      |    Verb phrase |
|      XP      |    Any phrasal unit (a slot that can be NP or VP or AP or PP) |

---

## 3. Правила записи имени конструкции

Слоты и морфологические характеристики в имени конструкции основаны на данных Национального корпуса русского языка. Когда корпусных данных оказывалось недостаточно, использовались результаты интернет-запросов.

Мы придерживаемся следующих правил в представлении синтаксической структуры конструкций.

1. Если конструкция содержит именную группу (NP), которая может употребляться не только в функции предикатива в именительном падеже, но и в других функциях (например, в роли объекта или инструмента), где она маркируется косвенным падежом, то падеж в формуле конструкции не указывается: **NP на нуле** (_Иммунитет на нуле_ vs. _Выписали пациента с иммунитетом на нуле_).

2. Если конструкция содержит именную группу (NP), которая употребляется в рамках этой конструкции только в предикативной функции и при связке в настоящем времени маркируется именительным падежом, то она указывается в формуле конструкции как NP-Nom (= именная группа с вершинным существительным в именительном падеже): **NP-Nom Cop NP-Nom VP-Inf** (_Он мастер готовить_).

3. Возможную замену именительного падежа на творительный для именной группы в предикативной функции при связке в прошедшем или будущем времени мы считаем общим правилом грамматики русского языка и указываем эту особенность в поле комментария с примерами: _Он был мастером готовить_.

4. Мы включаем связку в имя конструкции только в тех случаях, когда связка может употребляться в различных временны́х формах, а не только в настоящем времени: **NP-Nom Cop не очень** – _Для стоянки место не очень_ (прош.: _было не очень_; буд.: _будет не очень_).

5. Если конструкция содержит одиночное имя существительное, а не именную группу (NP), то в формуле конструкции оно указывается как Noun. Как правило, это касается конструкций с редупликацией имени существительного: **NP-Nom Cop всем Noun-Dat.Pl ~Noun-Nom** (_Всем борщам борщ!_)

6. Для предикатно-аргументных конструкций, которые содержат в якоре конкретный глагол, мы указываем, как выражается субъект, даже если он имеет стандартное маркирование с помощью именительного падежа: **NP-Nom знать толк в NP-Loc** (_Он знает толк в настольных играх_). Обычно якорный глагол дается в инфинитиве: это означает, что в этой конструкции он может употребляться в различных формах времени, лица и числа.  Так, в конструкции **NP-Nom знать толк в NP-Loc** инфинитив глагола _знать_ указывает на то, что этот глагол может употребляться и в других формах.

7. Если якорный глагол в составе данной конструкции может употребляться только в определенной грамматической форме (или в ограниченном наборе форм), то эти ограничения указаны в имени конструкции: **с PronPers-Gen хватит/хватило (NP-Gen)** (_С меня хватит_).

8. Если в якоре конструкции содержится глагол, который может употребляться в нескольких формах, ограниченных определенной морфологической характеристикой (видом, временем или другой глагольной категорией), то это указывается в имени конструкции. Например, в конструкции **найти-Pst NP-Acc!** (_Нашли развлечение!_) якорный глагол _найти_ употребляется только в прошедшем времени.

9. Если конструкция содержит глагольную группу (VP), то слот субъекта NP-Nom не указывается в формуле конструкции, поскольку падежное маркирование аргументов (включая логический субъект) зависит от модели управления конкретного глагола. Ср. **вечно VP**: _Вечно мне не везет_ (субъект имеет семантическую роль Экспериенцера и кодируется дательным падежом) vs. _Вечно Петр опаздывает_ (субъект имеет семантическую роль Агенса и кодируется именительным падежом).

10. Мы не указываем морфонологические варианты предлогов (например, _с_ и _со_) в имени конструкции. В таких случаях указывается только дефолтный алломорф: **VP с NP-Gen** (_Она с досады топнула ногой_).

---

## 4. Explanation of terms

### 4.1. Stylistic terms (Usage labels)

In the Russian Constructicon, we adopt a set of usage labels to mark those
constructions that are restricted to certain styles. The usage labels assigned
to constructions can therefore be used as guidelines for second language
learners.

If a construction is stylistically neutral and can be used in both informal and
formal situations, we do not mark it with a usage label. See the following
example of a neutral construction: **NP-Nom Cop похожий-Short на NP-Acc
(NP-Ins/по NP-Dat)** as in _Вася похож на папу_ ‘Vasja looks like his dad’.

If a construction is stylistically not neutral and therefore is restricted to a
certain usage domain, we mark it with one of three usage labels: either as
**Colloquial**, **Formal** or **Obsolete**.

Types of stylistically restricted constructions:

+ **Colloquial** – The construction has a colloquial flavor and is typically used
  in spoken Russian, particularly in informal situations: e.g. **(вот) то́-то и
  оно́, что Cl/XP** as in _То-то и оно, что от меня ничего не зависит_ ‘That’s
  just it, that nothing depends on my decision.’

+ **Formal** – The construction is commonly used in formal situations and written
  texts of formal style: e.g. **вследствие NP-Gen Cl** as in _Вследствие такого
  поведения наш договор аннулируется_ ‘As a result of such a behavior, our
  agreement is abrogated’.

+ **Obsolete** – The construction is obsolete and rarely used in Modern Russian:
  e.g. **(со)благоволить-Imp VP-Inf!** as in _Благоволите ответить!_ ‘Favor me
  with an answer!’

In the Russian Constructicon, there are no constructions tagged as Specialized.
In other words, there are no constructions that can only be used by speakers
who belong to a certain profession.

---

### 4.2. Syntactic terms

### 4.2.1. Syntactic type of construction

In the Russian Constructicon, we adopt a set of terms to tag syntactic types of
constructions:

+ **Biclausal Construction** – The construction contains two clauses. This tag is used first of all for annotation of paratactic biclausal structures. Such constructions consist of clauses that are placed one after another without connecting words: e.g. **кто
  бы ни VP-Pst, Cl**, as in _Кто бы ни звал её в кино, она не соглашалась_; **будучи NP-Ins, Cl**, as in _Будучи американцем, он мечтал разбогатеть_. Biclausal constructions with connecting words as well as biclausal constructions with matrix predicates are annotated with separate tags.

+ **Cl + Modifier Construction** – The construction contains an adverbial that modifies an entire clause: e.g. **как-то/что-то Cl**, as in _Что-то мне душно_.

+ **Cl/XP with parentheticals** – The construction contains a parenthetical, that is an expression with a discourse function that is syntactically not part of a clause: **само собой (разумеется), Cl**, as in _Само собой, мы придем на твой концерт_.

+ **Clause** – The construction constitutes an independent clause: e.g. **NP-Nom (как) давай VP-Inf**, as in _Он как давай петь_.

+ **Connection Construction** – The construction contains a conjunction or a combination of words that performs the function of a conjunction: **Cl благодаря тому, что Cl**, as in _Мы успели в аэропорт благодаря тому, что выехали заранее_; **сегодня ХP, (а) завтра XP**, as in _Зима в Москве суровая. Сегодня здоров, завтра – болен_.

+ **Copula Construction** – The construction contains a copula: e.g. **NP-Dat Cop пора VP-Inf**, as in _Мне пора идти в школу_.

+ **Discourse "Echo" Construction** – The construction refers to a relevant part of the previous discourse, often quoting a relevant lexeme in the same morphosyntactic form (thus creating an "echo" effect) and adding a comment: e.g. **Скажешь тоже – XP**, as in – _Он такой хороший! – Скажешь тоже – "хороший"!_

+ **Head + Modifier Construction** – The construction contains a head and its modifier; the head can be a VP, a NP or any other phrasal unit: e.g. **VP под
  рукой**, as in _У меня всегда есть запасной ключ под рукой_; **NP на имя NP-Gen**, as in _Нужно написать заявление на имя директора_.

+ **Matrix + Infinitival Complement Construction** - This is a subtype of the Predicate Argument Construction. The construction contains a matrix predicate that takes an infinitival complement without a complementizer. The matrix predicate can be a verb, a noun, an adjective or an adverb: **(NP-Dat) хочется/хотелось VP-Inf**, as in _Мне хочется уехать на море_; **готовность NP-Gen VP-Inf**, as in _Готовность родителей бороться поразила всех_; **Рад VP-Inf**, as in _Рада вас видеть!_; **NP-Nom Cop вправе VP-Inf**, as in _Он вправе сам решать, как ему жить_. The constructions with matrix predicates that take sentential complements with complementizers (_что_, _как_, _чтобы_, etc.) are tagged as a separate type (see a similar approach in Yoon & Wulff 2016 for Spanish, Arndt 2019 for English, see also Noonan 1985: 53 for discusssion of sentence-like vs. infinitive complements).

+ **Matrix + Sentential Complement Construction** – The construction contains a matrix predicate that has a valency for a sentential complement that can be represented by a finite or infinitival subordinate clause attached to the main clause by a complementizer (_что_, _как_, _чтобы_, etc.). It is often the case in our data that the same predicate allows for both types of sentential complements: e.g. **NP-Nom Cop за то, чтобы Cl/VP-Inf**, as in _Я за то, чтобы ты у нас жил_ (sentential complement is a finite clause) vs. _Я за то, чтобы поехать в отпуск_ (sentential complement is a non-finite clause). Other examples: **(все/вся) дело/суть Cop в том, что Cl**, as in _Дело в том, что она переживает трудные времена_; **знать-Fut, как VP-Ipfv.Inf!**, as in _Будет знать, как убегать от родителей!_; **NP-Nom и без NP-Gen знать, (что Cl)**, as in _Мы и без вас знаем, что делать_ vs. _Мы и без вас знаем, что нужно делать_. The constructions with matrix predicates that take infinitival complements without a complementizer are tagged as a separate type (see a similar approach in Yoon & Wulff 2016 for Spanish, Arndt 2019 for English among others, see also Noonan 1985: 53 for discusssion of sentence-like vs. infinitive complements).

+ **Morphological Construction** – The construction contains a specific derivational affix: e.g. **Adv-овато/-евато**, as in _После переезда в доме
  было пустовато_.

+ **Predicate Argument Construction** – The construction features the argument structure of a specific predicate or a type of predicate (verb, noun, adjective, participle): e.g. **NP-Nom тянуть с NP-Ins**, as in _Зачем тянуть с ответом?_; **главный/дежурный по NP-Dat**, as in _Главный по кухне_; **VP NP-Acc под NP-Acc**, as in _Однако после революции они переделали церковь под склад_.

---

### 4.2.2. Syntactic function of anchor (of the fixed part of construction)

+ **Argument** – The anchor can have various argument roles: e.g. **деньги на NP-Acc**, as in _Он откладывал деньги на покупку машины_ vs. _А кто меня защитит, кто поможет деньгами на хлеб_.

+ **Coordinator** – The anchor is a coordinating conjunction: e.g. **не прямо XP, а/но XP**, as in _Стоял не прямо перед зеркалом, а чуть в стороне_.

+ **Discourse Particle** – The anchor does not have any syntactic role and typically serves a discourse function, in the broad sense. It can be spelled as a separate word (_же, бы, ли_) or be hyphenated (_-таки, -то_): e.g. **Cl, NP же VP**, as in _Петя и Таня ушли, Маша же осталась нас поддержать_.

+ **Government** – The anchor is a noun phrase with specific case marking or a prepositional phrase governed by a verb, adjective, or words of other parts of speech: e.g. **NP-Nom выдавать NP-Acc за NP-Acc**, as in _Он выдавал себя за президента_; **Adj на NP-Acc (ради NP-Acc)**, as in _Способный на подвиг_.

+ **Matrix Predicate** – The anchor is a matrix predicate, that is a predicate that takes a sentential or infinitival complement: e.g. **(а) кто (это) сказал, что Cl**, as in _А кто сказал, что мы не хотим в кино?_; **что NP-Dat мешать VP-Inf?**, as in _Что ему мешало рассказать всю правду?_; **NP-Nom Cop вправе VP-Inf**, as in _Он вправе сам решать, как ему жить_.

+ **Modifier** – The anchor modifies a verbal or a nominal phrase: e.g. **VP изо всех сил**, as in _Ваня бежал изо всех сил_; **дикий Noun**, as in _Я испытал дикий ужас!_; **NP в NP-Acc**, as in _У него была тетрадь в клетку_.

+ **Nominal Quantifier** – The anchor is a nominal modifier specifying the number of objects: e.g. **уйма NP-Gen**, as in _На все расходы ушла уйма денег_.

+ **Object** – The anchor has the syntactic role of an object, either direct or indirect: e.g. **NP-Nom делать ошибки/сделать ошибку на NP-Acc**, as in _Вася постоянно делает ошибки на правило "жи ши пиши с буквой и"_; **Cl, а чего же (другого/ещё) PronPers-Nom ждать-Pst?**, as in _Конечно, она ушла, а чего же ты ждала?_.

+ **Parenthetical** – The anchor is a parenthetical element (word, phrase or clause) that does not serve any syntactic function in the clause it attaches to or is inserted in: e.g. **к слову (сказать), Cl**, as in _К слову, он тоже окончил этот факультет_.

+ **Praedicative Expression** – The anchor functions as a non-verbal predicate with a copula. This function can be performed by words categorized as predicatives in terms of their part of speech (e.g. _можно, пора, охота, холодно_) as well as by words of other classes used in predicative function with a copula (e.g. _студент, в стороне, в лом_): e.g. **(NP-Dat) Cop можно VP-Inf**, as in _Можно мне открыть окно?_; **NP-Nom Cop NP-Dat к лицу**, as in _Синее платье было ей к лицу_.

+ **Subject** – The anchor has the syntactic function of the subject of the clause: e.g. **я бы PronPers-Acc попросил VP-Inf**, as in _Я бы вас попросил не ругаться при детях_.

+ **Subordinator** – The anchor is a subordinating conjunction: e.g. **Cl, благодаря чему Cl**, as in _Грудное молоко имеет особую структуру, благодаря чему оно хорошо усваивается_.

+ **Verb Predicate** – The anchor is the verb predicate of the clause: e.g. **NP-Nom вести в NP-Acc**, as in _Дверь вела в комнату_.

+ **Word-Formation** – The anchor is a derivational affix: e.g. **NP-Nom пере-Verb-ся NP-Ins**, as in _Они перекидываются шутками_.

---

### 4.2.3. Syntactic structure of anchor (of the fixed part of construction)

+ **Argument Structure** - The anchor contains both the verb and its argument expressed by a prepositional phrase (or a preposition and specific case marking of the noun phrase): e.g. **NP-Nom знать NP-Acc по NP-Dat**, as in _Он знал актера по фильмам_; **NP-Nom краснеть за NP-Acc**, as in _Мама краснела за оценки сына_; **NP-Nom Cop близкий-Short к NP-Gen**, as in _Мы как никогда близки к победе_.

+ **Double Negation** - The construction contains two negation markers that can be separate words (_не, ни, нет_) or parts of a word (e.g. _никогда, ничуть_): e.g. **(NP-Dat) нельзя Cop не VP-Inf**, as in _Нельзя было не согласиться с ним тогда_; *никогда не VP**, as in _Я никогда не был в Африке_.

+ **Inversion** - The construction has a fixed word order that deviates from the default one: e.g. **рублей NumCrd**, as in _У Маши было рублей сто на книги_; **VP NP-Gen на NumCrd-Acc**, as in _Они уехали на дачу дня на два_.

+ **Light Verb Construction** - The construction contains a semantically bleached verb together with a noun (as a direct object or imbedded in a prepositional phrase). The verb typically has a very general meaning (e.g. _иметь, носить, брать, делать,_ etc.) and conveys grammatical meaning (tense, person, etc.), whereas the noun carries the lexical meaning: e.g. **держу пари, (что) Cl**, as in _Держу пари, что ты в него влюблена_; **NP-Nom носить/иметь Adj-Acc характер-Acc**, as in _Большинство звонков носило консультационный характер_; **оставить-Imp NP-Acc в покое!**, as in _Оставь меня в покое!_

+ **Multiword Conjunction** - The construction contains a conjunction that consists of two or more elements. The conjunction can be continuous or discontinuous depending on whether its parts are separated by other words in a sentence (cf. Шведова и др. 1980. Vol. 1, §1676): e.g. **Cl, в то время как Cl**, as in _Способность человека любить ограничена, в то время как потребность в любви – бесконечна_; **Cl не только Cl, но и Cl**, as in _Он был не только умён, но и добр_.

+ **Multiword Preposition** - The construction contains a preposition that consists of two or more elements. One of these elements is typically a simplex underived preposition (e.g. _согласно с, вдали от, по отношению к,_ etc. See Шведова et al. 1980. Vol. 1, §1656): e.g. **Cl в зависимости от NP-Gen**, as in _Уровень зарплаты определяется в зависимости от опыта работы_.

+ **Negation** - The construction contains a single negation marker: e.g. **(NP-Dat) не мешало бы/не мешает VP-Pfv.Inf**, as in _Нам не мешало бы подкрепиться_; **нет чтобы/бы VP-Inf, Cl**, as in _Нет чтобы подождать, он ушел без нас!_; **NP-Nom (это) Cop ещё ничего**, as in _Это ещё ничего_.

+ **Nominal Pattern** - The construction contains two nominal elements, where one word is the head and the other is dependent. The dependent nominal element always has a specific case marking and can be embedded in a prepositional phrase. Usually, both elements are nouns (the structure NP (Prep) NP), but an element can also be an adjective or a numeral. This structure can apply to both anchors and slots as its elements: e.g. **NP из-под NP-Gen**, as in _Коробка из-под торта_; **NP в NP-Loc**, as in _Боль в животе_; **человек NP-Gen**, as in _Человек трудной судьбы_.

+ **Not Applicable** – The construction lacks an anchor or has an anchor word or words that do not constitute any coherent structure: e.g. **будет PronPers-Dat (VP-Ipfv.Inf)!**, as in _Будет тебе врать!_; **Cl, а NP-Nom (опять) VP-Ipfv.Imp!**, as in _Он ушёл домой, а я опять переделывай всё после него_; **что же NP-Nom VP?**, as in _Что же он сидит?_

+ **Prepositional Phrase** - The construction contains an anchor that represents a prepositional phrase. Both the preposition and the noun are parts of the anchor: e.g. **(NP-Nom) это Cop в первую очередь NP-Nom**, as in _Это в первую очередь его заслуга_; **во всяком случае, Cl/XP**, as in _Во всяком случае, эксперты не исключают такого исхода событий_; **NP-Nom Cop на носу**, as in _Зима на носу_; **VP под шумок**, as in _Маша ушла под шумок_.

+ **Reduplication** - The construction contains repetition of the same morpheme or word (in the same or different morphological form). This structure can apply to both anchors and slots as its elements: e.g. **Noun-Nom есть ~Noun-Nom**, as in _Факт есть факт_; **NP-Nom по-Verb-по-~Verb и VP**, as in _Поспит-поспит и проснётся_; **NP-Nom ~NP-Ins, a NP-Nom ~NP-Ins**, as in _Дружба дружбой, а служба службой_; **вот-вот VP-Fut NP-Nom**, as in _Вот-вот прилетит самолет_; **всего-навсего NP**, as in _Это был всего-навсего старый диван_.

+ **Serial Verb Construction** - We recognize this type of structure according to the definition given by Haspelmath (2016: 292): "monoclausal construction consisting of multiple independent verbs with no element linking them and with no predicate–argument relation between the verbs"). E.g.: **NP-Nom сидеть VP**, as in _Сижу курю_; **NP-Nom Verb VP**, as in _Он идёт шатается_.

+ **Subject + Predicate** - This is a subtype of Argument Structure. The anchor contains both the subject and the predicate of the same clause: e.g. **чёрт знает PronInt**, as in _Чёрт знает как решать эту задачу!_; **что NP-Dat мешать VP-Inf?**, as in _Что ему мешало рассказать всю правду?_

+ **Verb + Object** - This is a subtype of Argument Structure. The anchor contains both the verb and its object argument: e.g. **(только) дать-Imp PronPers-Dat повод, Cl**, as in _Ему только дай повод, сразу придет просить_.

+ **Verb Pattern** - The construction contains two verbal elements, where one verb is the head and the other (usually an infinitive) is dependent. This structure can apply to both anchors and slots as its elements. We apply this tag to both matrix verbs with infinitival complements as well as to verbs that go with an infinitive of purpose or converbs that function as adjuncts of the main verb (cf. Тестелец 2001: 180): e.g. **а хотел бы PronPers знать/посмотреть/послушать, Sconj Cl**, as in _А хотел бы я знать, почему дети ещё не в постели!_; **NP-Nom бросить VP-Inf**, as in _Я бросил курить_; **NP-Nom за-Verb VP-Pfv.Inf**, as in _Я зашел поговорить_, **VP не переставая**, as in _Телефон звонит не переставая_.

---

### 4.2.4. Part of speech of anchor (of the fixed part of construction)

+ **Adjective** - A word that signifies a property of an object. An adjective modifies a noun and agrees with the noun (that is, an adjective alters its shape in order to match the grammatical categories of the noun). We apply this tag to both short and full forms of adjectives: e.g.: **NP-Nom Cop готовый-Short VP-Inf**, as in _Он готов открыть счёт в банке_.

+ **Adverb** – An uninflected word that modifies a verb, an adjective, an adverb, or a clause. Adverbs typically express manner, place, time, frequency, degree of intensity, degree of certainty, etc.: e.g. **примерно/приблизительно Prep NumCrd (NP-Gen)**, as in _Нужно приготовить супа примерно на восемь порций_.

+ **Conjunction** – A word that connects words, phrases, or clauses, including complex conjunctions (e.g. _несмотря на то, что_): e.g. **VP-Inf(-то) ~VP, а/но Cl**, as in _Спросить спрошу, но он может не знать_.

+ **Converb** – A nonfinite verb form that serves to express adverbial subordination (notions like 'when', 'because', 'after' and 'while'). A converb denotes an additional action associated with the main action expressed by the predicate. Converbs are uninflected and function as adjuncts that carry temporal, causal or other meanings: e.g. **Будучи NP-Ins, Cl**, as in _Будучи американцем, он мечтал разбогатеть_.

+ **Interjection** – A word that constitutes an utterance on its own and expresses a spontaneous feeling or reaction of the speaker: e.g. **ах PronPers-Nom NP-Nom!**, as in _Ах ты подлец!_

+ **Negation Marker** – _не_ or _ни_, a word that contains them (e.g. _никогда, некто, незачем_) and the word _нет_: e.g. **NP-Dat (не) Verb-ся**, as in _Мне не спится_.

+ **Not Applicable** – The construction does not have anchor words or contains an anchor word that is obsolete and no longer analyzable (e.g. _Бог весть_): e.g. **VP NP-Ins**, as in _Мы готовили обед всей семьей_.

+ **Noun** – A word that names something, such as a person, place, thing, abstract idea, etc.: e.g. **толпа NP-Gen.Pl**, as in _Толпа людей_.

+ **Numeral** – A word that describes a numerical quantity or the order of objects in the process of counting. The tag is used for cardinal, collective and ordinal numerals: e.g. **VP в двух словах**, as in _Он в двух словах рассказал про свою книгу_.

+ **Onomatopoeia** – A word that phonetically imitates or resembles the sound it describes: e.g. **Cl – и тю-тю/и тютю!**, as in _Он забрал машину – и тю-тю! Больше мы не встречались_.

+ **Participle** – A non-finite verb form that denotes a property associated with an action. Along with the features of a verb (aspect, tense, voice), this form has features of an adjective (gender, number, case) and agrees with a noun: e.g. **видавший виды NP**, as in _На видавшем виды велосипеде поехал дальше_.

+ **Particle** – An uninflected word that lacks referential content (as opposed to nouns, verbs, adjectives, etc.) and mostly serves discourse functions by conveying various modal and pragmatic attitudes of the speaker towards some information in a sentence: e.g. **VP же NP-Nom!**, as in _Живут же некоторые!_

+ **Predicative** – A word that denotes a state and acts as a predicate of an impersonal sentence including modals (e.g. _можно, надо,_ etc): e.g. **NP-Dat Cop пора VP-Inf**, as in _Мне пора идти в школу._

+ **Preposition** – A function word (or a group of words) governing, and usually preceding, a noun оr a pronoun to express a relation to another word or element in a sentence. This word usually conveys a meaning in the domain of time, location, direction, etc.: e.g. **NP-Nom Cop Adj-Nom до NP-Gen**, as in _Родители религиозные до фанатизма_.

+ **Pronoun** – A word that substitutes for nominal parts of speech (e.g. the pronouns _он_ и _кто_ substitute for a noun, the pronoun _этот_ substitutes for an adjective, _сколько_ substitutes for a numeral, and _когда_ substitutes for an adverb). We also use this tag for interrogative/relative pronouns and pronominal adverbs like _как_, _когда_: e.g. **И вот ещё что (Adv/VP): Cl**, as in _И вот ещё что: я к Маше не поеду_.

+ **Verb** – A word that indicates an action, event or state. We use this tag for finite verb forms and infinitives, whereas participles and converbs are annotated with other tags. We do not use this tag for desemanticized or obsolete forms that are not synchronically analyzable (e.g. _весть_ in _Бог весть кто_). E.g.: **PronPers-Nom PronPers-Dat дать VP-Inf!**, as in _Я тебе дам так себя вести!_

---

### 4.3. Semantic terms

Our system of semantic annotation includes 53 tags that describe general
semantic types of constructions and 157 secondary tags that specify their
sub-types. For explanations of individual semantic tags please use the
mouse-over function.
