### ISSUE TITLE
Instructions: The system of morphology tags in Advanced search

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#52]
## 2. Morphological terms

In Advanced Search, it is possible to search for constructions that contain slots and anchors restricted by certain morphological categories. In the search window, the morphological tags are listed in alphabetical order. The tables below offer an overview of these tags as a system. The first table lists the tags for grammatical categories, whereas the second table lists the tags for grammatical classes, that is parts of speech and syntactic units (which also indicate parts of speech). The third table lists the morphological tags that apply to several parts of speech.

We list the tags as full words and provide corresponding abbreviations that appear in the Advanced Search window in parentheses (). All items listed with bullet points and abbreviations are tags available in Advanced Search (Morphology), others are headings that organise them.

|Case |Gender|Number|Person|
|-----------------|-----------------|----------------|-------------------|
|• Nominative (Nom)|• Masculine (M)|• Singular (Sg)|• First person (1)|
|• Genitive (Gen)|• Feminine (F)|• Plural (Pl)|• Second person (2)|
|• Partitive genitive (Gen2)|• Neuter (N)|                |• Third person (3)|
|• Dative (Dat)|    **Tense**   |   **Aspect**   |   **Mood**   |
|• Accusative (Acc)|• Past (Pst)|• Perfective (Pfv)|• Imperative (Imp)|
|• Instrumental (Ins)|• Present (Prs)|• Imperfective (Ipfv)|• Subjunctive (Sbjv)|
|• Locative (Loc)|• Future (Fut)|               |              |

|Lexical parts of speech|Lexical parts of speech|Functional parts of speech|
|---------------------|---------------------|---------------------|
|• Bare noun (Noun)|   • Adverb (Adv) | • Interjection (Intj) |
|• Adjective (Adj)|   • Predicative (Pred) |• Preposition (Prep) |
|   Numeral: |   Verb: |      Conjunction: |
|   • Collective numeral (NumColl)|   • Auxiliary (Aux) |   • Coordinating conjunction (Cconj) |
|   • Cardinal numeral (NumCrd)|   • Bare stem (Bare) |• Subordinating conjunction (Sconj) |
|   • Ordinal numeral (NumOrd)|   • Copula (Cop) |**Syntactic units** |
|   Pronoun:|   • Converb (Cvb) |• Clause (Cl)|
|   • Demonstrative pronoun (PronDem)|   • Infinitive (Inf) |• Noun phrase (NP)|
|   •  Interrogative/relative pronoun (PronInt)|   • Active participle (PtcpAct) |• Prepositional phrase (PP)|
|   • Personal pronoun (PronPers)|   • Passive participle (PtcpPass) |• Verb phrase (VP)|
|   • Possessive pronoun (PronPoss) |   • Bare verb (Verb) |• Any phrasal unit (XP)|

|Morphology tags that apply to several parts of speech|
|---------------|
|• Comparative form of adjective or adverb (Cmp)|
|• Short form of adjective or participle (Short)|

Here is how these tables should ideally come out (these are the pdf versions made in ppt):

<img width="1024" alt="Screen Shot 2021-03-17 at 11 39 14" src="https://user-images.githubusercontent.com/63615172/111456924-db68ad00-8717-11eb-9c45-4a0f10b95fbb.png">

<img width="1031" alt="Table 2" src="https://user-images.githubusercontent.com/63615172/111612884-39f85e80-87de-11eb-9f27-14b35b755964.png">

We will go with tables in Markdown to make it user-friendly for blind users included.

**Comment by bast** [comment]
Problem with images is that they exclude visually impaired. But we can definitely place this there. I only need to know how you would like to arrange the page.

**Comment by Labrus** [comment]
Ok. Thank you for this. Laura says we should make it work for blind users too, so we will use tables in Markdown, I will slightly correct them and include in the Instructions as a separate section "Morphological terms".
