### ISSUE TITLE
Dependency Structure and Dependency Structure of Illustration are now in the database for all constructions

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#56]
This is rather a notification for you, hopefully not an additional "issue". Our colleague has now delivered the content for columns AJ and AK in the database. She insists on using the plus sign "+" as a separator for her strings of analyses. She explains this saying that both "," and ";" are used in these strings and cannot be separators. We hope this will still work with the "+", and if now, please let me know.
PS. For some constructions she has A LOT of strings that are motivated, as she says, by different alternatives for analysis. In other words, if you see this, it is not an error.

**Comment by bast** [comment]
I have now fixed the data importer to split on "+" and the "+" has higher priority than all other splitting characters. Let me know if something does not look right.

**Comment by Labrus** [comment]
Thank you for have worked on this issue! Having + as a separator has disturbed what we had so nicely in Advanced search: Syntactic type, where there are tags like "Head + Modifier Construction" and "Matrix + Infinitival Complement Construction", 
now they are split in parts.

<img width="600" alt="Screen Shot 2021-03-25 at 08 50 57" src="https://user-images.githubusercontent.com/63615172/112440902-25bae100-8d4b-11eb-9deb-c102ab48f85c.png">

I will talk to Laura hope we can rename these tags avoiding the use of + symbol, but if we change them, we will also have to change these names in the instructions text.

**Comment by Labrus** [comment]
We decided that I just modify how we spell the tags in Advanced search to avoid the + symbol, for example "Head + Modifier Construction" we will spell as "Head and Modifier Construction". This way you will not have to change anything in the programming that works fine now for UD analyses with +. I will make changes on the tags in the database and reflect this in the instructions on the website.
