### ISSUE TITLE
Draft of explanation of Advanced search: Morphology

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#57]
## 2. Advanced search: Morphology

In advanced search, it is possible to search for constructions that contain slots and anchors restricted by certain morphological categories. In the search window, the morphological tags are listed in alphabetical order. The table below offers an overview of these tags as a system. Here, we list the tags in full, and provide corresponding abbreviations that appear in the search window in parenthesis ().

|Case |Gender|Number|Person|
|-----------------|-----------------|----------------|-------------------|
|-Nominative (Nom)|- Masculine (M)|- Singular (Sg)|- First person (1)|
|-Genitive (Gen)|- Feminine (F)|- Plural (Pl)|- Second person (2)|
|-Partitive genitive (Gen2)|- Neuter (N)|                |- Third person (3)|
|-Dative (Dat)|                 |                |                   |
|-Accusative (Acc)|                 |                |                   |
|-Instrumental (Ins)|                 |                |                   |
|-Locative (Loc)|                 |                |                   |

|Aspect|Mood|Tense|
|----------|--------|-------|
|- Perfective (Pfv)|- Imperative (Imp)|- Past (Pst)|
|- Imperfective (Ipfv)|- Subjunctive (Sbjv)|- Present (Prs)| 
|               |              |- Future (Fut)|

|Lexical parts of speech|Lexical parts of speech|Functional parts of speech|
|---------------------|---------------------|---------------------|
|- Noun not forming an NP (Noun)|- Verb:         |- Preposition (Prep)            |
|- Adjective (Adj)|** Auxiliary (Aux)     |- Conjunction:|
|- Numeral: |** Bare (Bare)|** Coordinating conjunction (Cconj)|
|** Collective numeral (NumColl)|** Copula (Cop)  |** Subordinating conjunction (Sconj)|
|** Cardinal numeral (NumCrd)|** Converb (Cnv)       |- Interjection (Intj)           |
|** Ordinal numeral (NumOrd)|** Infinitive (Inf)    |**Syntactic units** |
|- Pronoun:|** Active participle (PtcpAct) |- Clause (Cl)|
|** Demonstrative pronoun (PronDem)|** Passive participle (PtcpPass) |- Noun phrase (NP)|
|** Interrogative/relative pronoun (PronInt)|** Verb not forming a VP (Verb)|- Prepositional phrase (PP)|
|** Personal pronoun (PronPers)|- Adverb (Adv)|- Verb phrase (VP)|
|** Possessive pronoun (PronPoss) |- Predicative (Pred)|- Any phrasal unit (XP)|

|Other|
|---------------|
|- Comparative (Cmp)|
|- Short form of an adjective or a participle (Short)|

**Comment by bast** [comment]
I can create the table and place it somewhere, I only need to know where you would like it to appear.

**Comment by Labrus** [comment]
Laura says it is fine how these tables look now in Instructions (Morphological terms), so we can close this issue.
