### ISSUE TITLE
Font and boldfacing

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#58]
The font of the text that you use now on the website makes very little difference between boldfaced text and non-boldfaced text. For example, in the passage below the names of member in the list are boldfaced and the title of the articles are boldfaced but one can almost not see the difference.

<img width="1133" alt="Screen Shot 2021-03-25 at 22 36 24" src="https://user-images.githubusercontent.com/63615172/112547251-ceecf000-8dba-11eb-9fc2-1a230546efed.png">

Is it possible to make the boldfacing more visible while using the same font? Is it possible to use a different font? For example, the one you used in Threat defuser website [https://threat-defuser.org] is very nice and easy to read.

**Comment by bast** [comment]
Yes that is easy to fix (through CSS).

**Comment by bast** [comment]
But are they really boldfaced? I don't see this in the source code: https://github.com/constructicon/russian/blob/main/content/about.md

**Comment by Labrus** [comment]
I replaced boldfacing with links in these examples (names of project members and titles of articles) a few days ago. 
But the lack of contrast between boldfaced and non.boldfaced text is there. Compare, for example, the boldfaced names of constructions in the text, boldfaced tags names in the instructions:

<img width="1129" alt="Screen Shot 2021-04-02 at 11 27 29" src="https://user-images.githubusercontent.com/63615172/113403199-8cbd4300-93a6-11eb-92f8-cc7eec9984df.png">

<img width="1137" alt="Screen Shot 2021-04-02 at 11 29 00" src="https://user-images.githubusercontent.com/63615172/113403274-a494c700-93a6-11eb-9f7d-8e00b2ccba03.png">

**Comment by Labrus** [comment]
For each font there is a scale of weight one can set, I found this scale for one of fonts [https://fonts.google.com/specimen/Roboto](url) One can probably choose a version with more weight for boldfacing to achieve more contrast between boldfaced and normal text.

**Comment by bast** [comment]
I changed the font/weight. Please check whether this looks better now.

**Comment by Labrus** [comment]
I really like this font. I think it is much easier to read. And now it is much better with boldfacing. But if possible, I would add even more thickness/weight to boldfacing to make the contrast more visible.

**Comment by bast** [comment]
We can make it bolder and it's your call but it looks very bold on my end. Please also check with another browser. Again, happy to change it.

**Comment by Labrus** [comment]
Thank you. I have now asked all project members and everyone is very happy with the font how it is now. Let us keep it this way.
