### ISSUE TITLE
Add Semantic type to what is in Additional information

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#60]
Semantic type has recently disappeared from the features that appear when the user presses the button "Show additional information" in description of a construction. Please place Semantic type back, locate it between PART OF SPEECH OF ANCHOR and SEMANTIC ROLES. The data that corresponds to Semantic type comes from columns AL-CL in the database.

<img width="801" alt="Screen Shot 2021-03-26 at 22 13 30" src="https://user-images.githubusercontent.com/63615172/112693270-a4656a80-8e80-11eb-8e83-527bf321d095.png">

**Comment by bast** [comment]
I don't think this was there before. I understand why it would be good to have it there but I think it was always missing because it is a bit more elaborate: it is not only a list but a nested list of possibly nested lists ...

**Comment by Labrus** [comment]
It would be great to have it, if possible.

**Comment by Labrus** [comment]
You can choose how to present it. It can come out as a nested list visually, as it will be in yaml, or it can be a string of tags with major tags and subtypes in () or (subtype ...) when the subtype is available: Main-tag-name (subtype Tag-name). If it is easier to program as a string and not a nested list, it is fine for us too.
