### ISSUE TITLE
Remove quotation marks that embrace the text we put in References

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#62]
<img width="1139" alt="Screen Shot 2021-03-26 at 22 26 39" src="https://user-images.githubusercontent.com/63615172/112694354-826ce780-8e82-11eb-8eec-25614c364254.png">

References is the last part of description of each construction and appears as Additional information.
 Now, the text we put there becomes embraced with the " " on both sides. If possible please remove these symbols.

This applies to all constructions. If there is no reference, the symbol " " is still there. Please remove this symbol everywhere.

**Comment by Labrus** [comment]
One more image to show where References appear:

<img width="1168" alt="Screen Shot 2021-03-26 at 22 30 51" src="https://user-images.githubusercontent.com/63615172/112694638-fb6c3f00-8e82-11eb-8a4f-371afe2f0ed4.png">

**Comment by bast** [comment]
Putting it on my list.

**Comment by bast** [comment]
Solved now (fixed in the data repository).

Next time when providing examples, please give me the numbers, then I find them immediately :-)
