### ISSUE TITLE
Remove the apostrophe symbols in the beginning and the end of each example in EXAMPLES

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#63]
If possible please remove the apostrophe symbols that appear now at the very beginning and the very end of each example of each construction. - in EXAMPLES in descriptions of constructions

<img width="1174" alt="Screen Shot 2021-03-26 at 22 30 42" src="https://user-images.githubusercontent.com/63615172/112694694-12ab2c80-8e83-11eb-934e-b2a4a9bdb250.png">

**Comment by bast** [comment]
This will probably be easy to fix.

**Comment by bast** [comment]
Solved now (fixed in the data repository).
