### ISSUE TITLE
Symbol "\n" in DEPENDENCY STRUCTURE OF ILLUSTRATION and DEPENDENCY STRUCTURE

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#64]
The colleague responsible for DEPENDENCY STRUCTURE (UD) informed me that she used the symbol "\n" to indicate sentence boundary in her data and said that when putting this on the website, this symbol "\n" should be replaced with a space. In other words, what precedes "\n" and what follows "\n" should appear in the same line and a space should be between them instead of "\n". Is this possible to program?

Example- construction 1247
NAME хорош VP-Ipfv.Inf! - Эй, наверху! Хорош прыгать!

<img width="419" alt="Screen Shot 2021-03-30 at 10 38 54" src="https://user-images.githubusercontent.com/63615172/112959932-381a8d80-9144-11eb-84b0-e6d68b53c58c.png">

**Comment by bast** [comment]
Yes this can be done but "\n" normally means newline, not a space so I recommend to not use this to indicate space. But I can work around this.

**Comment by bast** [comment]
Solved now (fixed in the data repository).
