### ISSUE TITLE
Problem with "," in DEPENDENCY STRUCTURE OF ILLUSTRATION

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#65]
I have noticed a problem: a comma symbol without spaces around it still reads as a separator in DEPENDENCY STRUCTURE OF ILLUSTRATION and this leads to incorrect representation of the structure.
I use the same example construction 1247
NAME хорош VP-Ipfv.Inf! - Эй, наверху! Хорош прыгать!

In the database (column AK) the structure for this is:
[root [parataxis Эй],наверху!]\n[root Хорош [csubj прыгать]!]

There is no spaces around in the sequence: Эй],наверху!
Still, "," is read as a separator and outcome representation on the website splits this single line in two lines as follows:

<img width="419" alt="Screen Shot 2021-03-30 at 10 38 54" src="https://user-images.githubusercontent.com/63615172/112960299-90ea2600-9144-11eb-9490-da3879726be2.png">

This should come out as a single line. 
I am very sorry for all these numerous complications for you Radovan!!!!!

**Comment by bast** [comment]
This is the price we pay for inconsistent separator definitions. I am adding more and more exceptions and ifs and unless-es and we will see some edge cases "falling through". I will try to adapt for this.

**Comment by bast** [comment]
Is there a different meaning/intent of "," versus ", " in the spreadsheet?

**Comment by bast** [comment]
And what is the separator character for this column if it is not ","?

**Comment by Labrus** [comment]
I see that in the database ", " (comma with space) is used inside Names of constructions (column E), illustrations (column G) as not a separator. But in column Q (Morphology), columns R, S, T, U, AD, AG, AH ", " is used to separate between different tags. I see now that this probably presents a problem for programming. I can replace the ", " as a separator in this columns with "; " if this can help. I see that in the columns AJ (Dependency Structure) and and AK (Dependency Structure of Illustration) ", "  is also used, and it is not a separator but at comma inside sentences. She used only "+" as a separator there.

**Comment by bast** [comment]
No need to change the spreadsheet. I can adapt the conversion.

**Comment by bast** [comment]
It's still not clear to me: Let us focus now only on "DEPENDENCY STRUCTURE OF ILLUSTRATION". Does this column have any separators in the text on which I should chop it up? And if yes, what are these separators?

**Comment by Labrus** [comment]
The only separator in this column is "+". Punctuation marks are not separators there, that is why that colleague chose the plus symbol as a separator.
In other words, comma should not be understood here as a separator, it is not. 
So, for construction 1247 NAME хорош VP-Ipfv.Inf! - Эй, наверху! Хорош прыгать!, the DEPENDENCY STRUCTURE OF ILLUSTRATION" is spelled as [root [parataxis Эй],наверху!]\n[root Хорош [csubj прыгать]!] and it should come out as a single line.

**Comment by bast** [comment]
This is now fixed (in russian-data repository).
