### ISSUE TITLE
Instructional video on the website

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian#71]
In the grant Laura promised to provide an instructional video for the website of Constructicon. So she now wants to use the launch video that we prerecorded in zoom (about 12 min long) as an instructional video and upload it somehow on the website. It belongs to Instructions (English) page, so maybe we could put it there after the list of contents (in blue) before the text of instructions starts. Or where could it fit better? What do you think? Should we first upload this video to the conference YouTube channel and then add the link to Constructicon website or can we just upload the video on the website like a picture?

<img width="1230" alt="Screen Shot 2021-04-16 at 21 45 05" src="https://user-images.githubusercontent.com/63615172/115076592-115aa600-9efd-11eb-8761-dba1c2fb742d.png">

**Comment by bast** [comment]
I think best to place it on YouTube and link to it with a preview window. We cannot upload it to GitHub.

**Comment by Labrus** [comment]
Our assistant has now uploaded the video ion YouTube channel created for the conference.
here is the link https://www.youtube.com/watch?v=gS70MpJPN9o
